/**
 * FrpcAdapter - frpc 进程适配器
 * 
 * 封装 frpc 特定逻辑：
 * - 版本验证与二进制 hash 校验
 * - TOML 配置生成（使用 env 模板，不写真实 token）
 * - 日志解析与错误分类
 * - 连接状态检测
 */

import { ManagedProcess, ManagedProcessOptions } from "./managed-process";
import { createHash } from "node:crypto";
import { EventEmitter } from "node:events";
import { readFileSync, existsSync } from "node:fs";

export interface FrpcProfile {
  /** 服务器地址 */
  serverAddr: string;
  /** 服务器端口 */
  serverPort: number;
  /** 代理名称 */
  proxyName: string;
  /** 本地地址 */
  localAddr: string;
  /** 本地端口 */
  localPort: number;
  /** 远程端口 */
  remotePort: number;
  /** 协议类型 */
  protocol: "tcp" | "udp";
}

export interface FrpcConfig {
  /** 配置文件路径（TOML） */
  configPath: string;
  /** frpc 二进制路径 */
  binaryPath: string;
  /** 期望的二进制 hash（SHA-256） */
  expectedHash?: string;
  /** frpc 版本 */
  version: string;
  /** Override command arguments for a platform wrapper or an isolated test. */
  args?: string[];
}

export type FrpcErrorCategory = 
  | "auth_failed"
  | "proxy_conflict"
  | "config_error"
  | "binary_error"
  | "network_error"
  | "unknown";

export interface FrpcError {
  category: FrpcErrorCategory;
  message: string;
  retryable: boolean;
  raw?: string;
}

export class FrpcAdapter extends EventEmitter {
  private process: ManagedProcess | null = null;
  private logBuffer: string[] = [];
  private readonly MAX_LOG_LINES = 100;
  private readonly redactedValues = new Set<string>();
  private pendingLogChunk = "";
  private errorEventCount = 0;

  constructor(private config: FrpcConfig) {
    super();
    // Validate binary exists and hash matches
    this.validateBinary();
  }

  /**
   * 验证 frpc 二进制文件
   */
  private validateBinary(): void {
    if (!existsSync(this.config.binaryPath)) {
      throw new Error(`frpc binary not found: ${this.config.binaryPath}`);
    }

    if (this.config.expectedHash) {
      const binaryContent = readFileSync(this.config.binaryPath);
      const hash = createHash("sha256").update(binaryContent).digest("hex");
      if (hash !== this.config.expectedHash) {
        throw new Error(
          `frpc binary hash mismatch: expected ${this.config.expectedHash}, got ${hash}`
        );
      }
    }
  }

  /**
   * 生成 frpc TOML 配置（使用环境变量模板）
   */
  static generateToml(profile: FrpcProfile, tokenEnvVar: string): string {
    return `# frpc configuration
# Generated by pi-web-desktop
# Token is injected via environment variable, not stored in config

user = "{{ .Envs.FRPC_USER }}"
serverAddr = "${profile.serverAddr}"
serverPort = ${profile.serverPort}

transport.tls.enable = true

[[proxies]]
name = "${profile.proxyName}"
type = "${profile.protocol}"
localIP = "${profile.localAddr}"
localPort = ${profile.localPort}
remotePort = ${profile.remotePort}

# Authentication
transport.tls.trustServerCert = true
auth.method = "token"
auth.token = "{{ .Envs.${tokenEnvVar} }}"
`;
  }

  /**
   * 启动 frpc 进程
   */
  async start(profile: FrpcProfile, token: string): Promise<void> {
    if (this.process) {
      throw new Error("frpc already running");
    }

    const env = {
      ...process.env,
      FRPC_USER: profile.proxyName,
      FRPC_TOKEN: token,
    };
    this.redactedValues.add(token);
    this.pendingLogChunk = "";

    const options: ManagedProcessOptions = {
      command: this.config.binaryPath,
      args: this.config.args ?? ["-c", this.config.configPath],
      env,
      name: "frpc",
      startTimeoutMs: 15000,
      stopTimeoutMs: 5000,
      autoRestart: true,
      readinessCheck: () => this.checkReadiness(),
      readinessIntervalMs: 500,
      readinessTimeoutMs: 15000,
    };

    this.process = new ManagedProcess(options);

    // Listen to process events
    this.process.on("exited", () => {
      this.flushPendingLog();
      const error = this.classifyError();
      if (!error.retryable) this.process?.block(`frpc_${error.category}`);
      this.errorEventCount += 1;
      this.emitFrpcError(error);
    });

    this.process.on("stateChange", ({ from, to }) => {
      this.emit("stateChange", { from, to });
    });
    this.process.on("stdout", ({ data }) => this.appendLog(data));
    this.process.on("stderr", ({ data }) => this.appendLog(data));

    const errorCountBeforeStart = this.errorEventCount;
    try {
      await this.process.start();
    } catch (err) {
      // A process can fail before emitting an exit event (for example a spawn
      // error). Surface that case without duplicating an already-classified
      // child exit.
      if (this.errorEventCount === errorCountBeforeStart) {
        this.emitFrpcError(this.classifyError());
      }
      throw err;
    }
  }

  /**
   * 停止 frpc 进程
   */
  async stop(): Promise<void> {
    if (!this.process) {
      return;
    }

    await this.process.stop();
    this.process = null;
  }

  /**
   * 检查 frpc 是否就绪
   */
  private async checkReadiness(): Promise<boolean> {
    // start() remains in "starting" until this probe succeeds. Therefore a
    // readiness probe must check child liveness, not running health.
    if (!this.process || !this.process.isAlive()) {
      return false;
    }

    // Check logs for success indicators
    const logs = this.getLogBuffer();
    const hasSuccess = logs.some((line) => 
      line.includes("start proxy success") ||
      line.includes("login to server success")
    );

    const hasError = logs.some((line) =>
      line.includes("authorization failed") ||
      line.includes("connection refused") ||
      line.includes("EOF")
    );

    if (hasError) {
      return false;
    }

    return hasSuccess;
  }

  /**
   * 分类错误
   */
  private classifyError(): FrpcError {
    const logs = this.getLogBuffer();
    const logText = logs.join("\n");

    // Auth errors
    if (logText.includes("authorization failed") || logText.includes("authentication failed")) {
      return {
        category: "auth_failed",
        message: "frpc 认证失败，请检查 token",
        retryable: false,
        raw: logText,
      };
    }

    // Proxy conflict
    if (logText.includes("remote port is already used") || logText.includes("proxy name conflict")) {
      return {
        category: "proxy_conflict",
        message: "远程端口已被占用，请更换端口或关闭旧实例",
        retryable: false,
        raw: logText,
      };
    }

    // Config errors
    if (logText.includes("invalid config") || logText.includes("parse config")) {
      return {
        category: "config_error",
        message: "frpc 配置错误",
        retryable: false,
        raw: logText,
      };
    }

    // Network errors
    if (logText.includes("connection refused") || logText.includes("timeout") || logText.includes("EOF")) {
      return {
        category: "network_error",
        message: "网络连接失败，请检查服务器地址和端口",
        retryable: true,
        raw: logText,
      };
    }

    return {
      category: "unknown",
      message: "frpc 未知错误",
      retryable: true,
      raw: logText,
    };
  }

  private appendLog(chunk: string): void {
    const lines = (this.pendingLogChunk + chunk).split(/\r?\n/);
    this.pendingLogChunk = lines.pop() ?? "";
    for (const line of lines) this.commitLogLine(line);
  }

  private flushPendingLog(): void {
    if (!this.pendingLogChunk) return;
    this.commitLogLine(this.pendingLogChunk);
    this.pendingLogChunk = "";
  }

  private commitLogLine(line: string): void {
    if (!line.trim()) return;
    const redacted = this.redactLog(line.trim());
    this.logBuffer.push(redacted);
    this.emit("log", { line: redacted });
    while (this.logBuffer.length > this.MAX_LOG_LINES) {
      this.logBuffer.shift();
    }
  }

  private redactLog(line: string): string {
    let redacted = line;
    for (const value of this.redactedValues) {
      if (value) redacted = redacted.split(value).join("[REDACTED]");
    }
    return redacted.replace(/\b(token|authorization)\s*[:=]\s*[^\s,;]+/gi, "$1=[REDACTED]");
  }

  private emitFrpcError(error: FrpcError): void {
    this.emit("frpcError", error);
    // Node treats an unhandled "error" event as an exception. Preserve the
    // conventional event for subscribers without making a failed tunnel crash
    // a caller that only awaits start().
    if (this.listenerCount("error") > 0) this.emit("error", error);
  }

  /**
   * 获取日志缓冲区
   */
  getLogBuffer(): string[] {
    // A readiness message can be split across pipe chunks and not end in a
    // newline yet. Include the accumulated fragment for matching, but redact
    // it before it leaves the adapter.
    const pending = this.pendingLogChunk.trim();
    return pending ? [...this.logBuffer, this.redactLog(pending)] : [...this.logBuffer];
  }

  /**
   * 获取当前状态
   */
  getStatus(): { running: boolean; pid: number | null; logs: string[] } {
    if (!this.process) {
      return { running: false, pid: null, logs: [] };
    }

    const status = this.process.getStatus();
    return {
      running: status.state === "running",
      pid: status.pid,
      logs: this.getLogBuffer(),
    };
  }

}
